### ISSUE TITLE
Download not working.

### ISSUE THREAD

**Issue by sorenwacker** [mzmine/mzmine_documentation#108]
Hi, I tried to download Mzmine3, but it seems that the link is not working. I also get a warning regarding the SSL certificate:

![image](https://user-images.githubusercontent.com/3391614/236527708-1b7d92c5-94dc-4904-a101-44b895ca456d.png)

**Comment by tomas-pluskal** [comment]
It seems to be working fine, are you sure this was not a temporary connection issue? Have you tried accessing it from a different computer?

**Comment by sorenwacker** [comment]
No, it is still not working. Maybe it is my browser. I am using Chrome.

![image](https://user-images.githubusercontent.com/3391614/236693934-efa321cc-29a9-493c-b843-f8ad0a5c2b90.png)

Nothing happens when I click on download.

http://mzmine.github.io/download.html

**Comment by sorenwacker** [comment]
I experience both, download issue and certificate warning also with Firefox.

**Comment by tomas-pluskal** [comment]
Try replacing http with https:
https://mzmine.github.io/download.html
Where did you find the http link?
