### ISSUE TITLE
Windows for "Aducts" and "Modifications" do not appear for ion identity networking

### ISSUE THREAD

**Issue by bsedio** [mzmine/mzmine_documentation#72]
Hello MZmine,

I am running MZmine 3.2.8 on a Mac OS 12.6 Monterey. When I open "ion identity networking" and "ion identity library:setup" the windows under "Aducts" and "Modifications" do not render, and hence no aducts can be selected and the ion identity networking module does not execute. A screenshot is attached. 
<img width="859" alt="Screen Shot 2022-10-12 at 3 38 15 PM" src="https://user-images.githubusercontent.com/83842383/195443184-aee73026-c26a-4bf1-8359-70f65f3ffafe.png">

Is this an error in MZmine3? Or am I doing something wrong that is preventing the window for selecting aducts to render?

Thank you very much,
Brian

**Comment by SteffenHeu** [comment]
there are no adducts/modifications present by default. click "reset positive/negative" and "reset" do use the default list.

if this issue persists, please use the MZmine repository to report it: https://github.com/mzmine/mzmine3/issues
this is just for the documentation.
